---
title: "Intermediate R"
author: "Fall 2024"
date: "9/21/2024"
output: 
  prettydoc::html_pretty:
  #html_document:
    toc: true
    #number_sections: true
    toc_depth: 4
    theme: cayman
    #toc_float: true
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

```


The goal for the fall quarter is to diver deeper into R, R Studio, and Github, and explore what these have to offer you as young scientists. 

# Lesson 1 - R Projects, File Organization, and Naming Schematics

Last year, we talked about several ways to set your working directory, including using the command line in your console, manually, and by using R Projects. 

*Why should you use R projects?*

* Keeps all your files that are related to your project all in one place, including your data files, your code files, any output, etc.

* Sets your working directory to the file directory

* Keeps your project in the exact state that you left it in, including keeping your windows open.

* Allows you to easily call your files using the `here` package without having to write in an entire file pathway, which is specific only to **your** computer. This makes it difficult to collaborate with multiple people and is not good coding practice.

*Why should you spend time organizing your files?*

Organizing your files in a way that makes sense will allow you to have the most efficient workflow. Once you have an R project, you can organize your files into sub-folders within. When I make an R Project, the first folder that I create within are:

* Code - this is where I keep all my Rmd, R, and HTML output files

* Data - this is where I put all csv files (both files for input and output csv files)

* Images or Output - this is where I put any files that I created throughout my work

*Why should you think carefully about naming schematics?*

Naming your files and object intuitively will allow you to easily navigate your code, and will allow your collaborators to know what is going on. If you name your model `model1`, that doesn't really convey what you are working on. If you name your Blue Rockfish dataframe `brd` that only works for you... if you even remember that is why you named your dataframe that. If you name your code file `code`, you wont remember what is contained within.

Here are a few best coding practices to consider:

* If you are going to have multiple files that you want to organize in chronological order, consider naming the file with the date first *starting with the year like every other country except the US*.

  * 2024-09-21_


### Lesson activity 1 - make an R project

### Lesson activity 2 - create subfolders to organize files




