---
title: "R Basics"
author: "Fall 2023 - BIO 503"
date: "10/10/2023"
output: 
  prettydoc::html_pretty:
  #html_document:
    toc: true
    #number_sections: true
    toc_depth: 4
    theme: cayman
    #toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = F,
                      warning = F)
```


## Lesson 1 - R, RStudio, Working Directories, Data

R is a programming language that is a very valuable tool for biologist and ecologists. It is a powerful statistical program that also allows the user to create publication-quality figures. 



### Installing R and RStudio

First, everyone should have R and RStudio installed on their computers. Here are some links to do that: https://cran.r-project.org/ (obviously... download R for windows if you have a PC or R for macOS if you are a plebian.)

### The RStudio interface

### The difference between your script and your console

### Setting your working directory (WD)

### Reading in your data




## Lesson 2 - Transforming your data

### filter()

### arrange()

### select()

### group_by() and summarise()

### count(), rename(), and mutate()

### mutate() with case_when() a.k.a. the 'if then' statement


## Lesson 3 - Statistics examples


## Lesson 4 - Visualization

### "geometries"
